// vue-temp/old3/src/components/TodoItem.vue
<template>
  <li>
    <span :class="{done: todo.completed}">
      <input type="checkbox" v-on:change="todo.completed = !todo.completed">
      <strong>{{ idx + 1 }}</strong>
      {{ uppercase }}
    </span>
    <button class="rm"
            v-on:click="$emit('rm-todo', todo.id)"
    >&times;
    </button>
  </li>
</template>

<script>
export default {
  props: {
    todo: {
      type: Object,
      required: true
    },
    idx: Number
  },
  computed: {
    uppercase() {
      return this.todo.title.toUpperCase()
    }
  }
}
</script>

<style scoped>
li {
  border: 1px solid #ccc;
  display: flex;
  justify-content: space-between;
  padding: .5rem 2rem;
  margin-bottom: 1rem;
}

.rm {
  background: red;
  color: #fff;
  border-radius: 50%;
  font-weight: bold;
}

.done {
  text-decoration: line-through;
}

input {
  margin-right: 1rem;
}
</style>

// react-temp/src/todo/TodoItem.js
/*
 * "Maestro": Reminder and notepad project.
 *
 * Copyright 2022
 */

import React from "react";
import PropTypes from 'prop-types'

const styles = {
    li: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: '.5rem 1rem',
        border: '1px solid #ccc',
        borderRadius: '4px',
        marginBottom: '.5rem'
    },
    input: {
        marginRight: '1rem'
    }
}

function TodoItem({todo, idx, onChange}) {
    const classes = []

    if (todo.completed) {
        classes.push('done')
    }

    return (
        <li style={styles.li}>
            <span className={classes.join(' ')}>
                <input
                    type="checkbox"
                    checked={todo.completed}
                    style={styles.input}
                    onChange={() => onChange(todo.id)}
                />
                <strong>{idx + 1}</strong>
                &nbsp;
                {todo.title}
            </span>


            <button className='rm'>&times;</button>
        </li>
    )
}

TodoItem.propTypes = {
    todo: PropTypes.object.isRequired,
    idx: PropTypes.number,
    onChange: PropTypes.func.isRequired
}

export default TodoItem
